name: Count 

on:
  push:
  pull_request:
    branches: ['**']     # any target branch
    paths: ['**']        # any files changed
    types: [opened, synchronize, reopened, ready_for_review]



  workflow_dispatch:

  #MIN HOUR DAY MONTH WEEKDAY
  #12:00 IST → 06:30 UTC → cron: '30 6 * * *'
  schedule:
    # Daily at 09:00 IST (UTC+5:30) -> 03:30 UTC
    - cron: '30 3 * * *'

permissions:
  contents: write

env:
  Global_Var: "Global Workflow Variable"


jobs:
  

  fail-job-count:
    runs-on: ubuntu-latest
    env:
      Zone: "Asia/Kolkata"

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Create folder
        run: |
          
          if [ -d "textfolder" ]; then
            echo "File and Folder Exist!"
          else
            mkdir -p textfolder
            echo "This file contains zone time, date and Job"> textfolder/Count.txt
            echo "File and Folder Created Successfully!"
          fi
          
      - name: Failed Job Count
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FAILED= $(gh api repos/${{github.repository }}/actions/runs \ --jq '.workflow_runs[] |select(.conclusion =="failure") | .id | wc -l)

          echo "Failed Jobs Count: $FAILED"
        

      # - name: Write timestamp and event info
      #   run: |
      #     export TZ="Asia/Kolkata"
      #     NOW="$(date '+%Y-%m-%d %H:%M:%S %Z')"
      #     echo "--------------------------------------------------------" >> textfolder/timestamp.txt
      #     echo "Event: ${{ github.event_name}}" >> textfolder/timestamp.txt
      #     echo "Repository: ${{ github.repository}}" >> textfolder/timestamp.txt
      #     echo "Branch: ${{ github.ref_name}}" >> textfolder/timestamp.txt
      #     echo "Changed file(s): ${CHANGED_FILES}" >> textfolder/timestamp.txt
      #     echo "Triggered at (IST): ${NOW}" >> textfolder/timestamp.txt
      #     echo "--------------------------------------------------------" >> textfolder/timestamp.txt
          
      # - name: Commit changes
      #   run: |
      #     git config user.name "Ankit-Kumar-Bayer"
      #     git config user.email "ankit.kumar9.ext@bayer.com"

      #     git add textfolder/timestamp.txt
      #     git commit -m "Update timestamp from ${{github.event_name}}" || echo "No Commit"
      #     git push
